/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.utl.dsm.vista;

import java.io.IOException;
import javax.swing.JLabel;
import org.utl.dsm.controllerArduino.ConexionArduino;

/**
 *
 * @author alonv
 */
public class main extends javax.swing.JFrame {

    ConexionArduino c;
    Leer leer;
    Leer2 leer2;

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
        this.inicializar();
        leer = new Leer(numeroLuz);
        leer2 = new Leer2(numeroCm);
        leer2.start();
        leer.start();

    }

    public void inicializar() {
        try {
            this.numeroLuz.setText("0");
            this.numeroCm.setText("0");
            c = new ConexionArduino();
            c.conexion("COM3", 9600);
            c.busDatos();
            estadoArduino.setText("Se conceto Exitosamente");

        } catch (Exception e) {
            estadoArduino.setText("Error con el puerto o Arduino no conectado");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        numeroLuz = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        estadoArduino = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Distancia = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        numeroCm = new javax.swing.JLabel();

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Nivel actual de luz:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(600, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(0, 153, 153));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Nivel actual de luz:");

        numeroLuz.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        numeroLuz.setForeground(new java.awt.Color(0, 0, 0));
        numeroLuz.setText("Luz");

        jLabel4.setText("Estado Arduino:");

        estadoArduino.setText("Estado##");

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Distancia al objeto mas cercano:");

        Distancia.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        Distancia.setForeground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sensor de luz con java");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel1)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        numeroCm.setFont(new java.awt.Font("Yu Gothic UI", 0, 36)); // NOI18N
        numeroCm.setForeground(new java.awt.Color(0, 0, 0));
        numeroCm.setText("cm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(estadoArduino))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(numeroCm))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(numeroLuz)
                                .addGap(435, 435, 435)
                                .addComponent(Distancia))))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(numeroLuz)
                    .addComponent(Distancia))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(numeroCm))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(estadoArduino)
                .addGap(12, 12, 12))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);

            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Distancia;
    private javax.swing.JLabel estadoArduino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel numeroCm;
    private javax.swing.JLabel numeroLuz;
    // End of variables declaration//GEN-END:variables

    class Leer extends Thread {

        private boolean x = true;
        private JLabel numeroLuz;

        public Leer(JLabel numeroLuz) {
            this.numeroLuz = numeroLuz;
        }

        @Override
        public void run() {
            while (x) {
                try {
                    String valorLuz = c.recibeArduino();
                    procesarValorLuz(valorLuz, numeroLuz);

                } catch (IOException ex) {
                    handleException(ex);
                } catch (Exception ex) {
                    handleException(ex);
                }

                sleepThread();
            }
        }

        private void procesarValorLuz(String valorLuz, JLabel textField) {
            try {
                String[] separarValores = valorLuz.split(",");
                System.out.println(valorLuz);
                if (valorLuz != null && !valorLuz.isEmpty()) {
                    textField.setText(separarValores[1]);
                } else {
                    System.out.println("No se recibe nada");
                }
            } catch (Exception ex) {
                handleException(ex);
            }
        }

        private void handleException(Exception ex) {
            estadoArduino.setText("Ocurrió un error");
            ex.printStackTrace();
        }

        private void sleepThread() {
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }

    class Leer2 extends Thread {

        private JLabel numeroCm;

        public Leer2(JLabel numeroCm) {
            this.numeroCm = numeroCm;
        }

        @Override
        public void run() {
            while (true) {
                try {
                    String valorLuz = c.recibeArduino();
                    procesarValorLuz(valorLuz, numeroCm);

                } catch (IOException ex) {
                    handleException(ex);
                } catch (Exception ex) {
                    handleException(ex);
                }

                sleepThread();
            }
        }

        private void procesarValorLuz(String valorLuz, JLabel textField) {
            try {
                String[] separarValores = valorLuz.split(",");
                System.out.println(valorLuz);
                if (valorLuz != null && !valorLuz.isEmpty()) {
                    textField.setText(separarValores[0]);
                } else {
                    System.out.println("No se recibe nada");
                }
            } catch (Exception ex) {
                handleException(ex);
            }
        }

        private void handleException(Exception ex) {
            estadoArduino.setText("Ocurrió un error");
            ex.printStackTrace();
        }

        private void sleepThread() {
            try {
                Thread.sleep(100);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
    }
}
